
import { Connector } from '../../types';

// --- Operator Configuration Area ---
// Developers/Operators add new official integrations here.
// This serves as the "System Preset" list.

export const SYSTEM_CONNECTORS: Connector[] = [
    // --- Apps (Personal Integrations) ---
    { 
        id: 'browser', 
        name: 'My Browser', 
        description: 'Allow Manus to access your personalized context and execute tasks directly in the browser.', 
        providerId: 'browser', 
        category: 'all', 
        status: 'available', 
        type: 'app',
        version: '1.0', 
        color: 'bg-white',
        authType: 'oauth',
    },
    { 
        id: 'gmail', 
        name: 'Gmail', 
        description: 'Compose emails, search conversations, and generate summaries quickly.', 
        providerId: 'gmail', 
        category: 'all', 
        status: 'available', 
        type: 'app',
        version: 'v1', 
        color: 'bg-red-50 text-red-700',
        authType: 'oauth',
    },
    { 
        id: 'google_calendar', 
        name: 'Google Calendar', 
        description: 'View schedule, optimize time, and manage events.', 
        providerId: 'google_calendar', 
        category: 'all', 
        status: 'available', 
        type: 'app',
        version: 'v3', 
        color: 'bg-blue-50 text-blue-700',
        authType: 'oauth',
    },
    { 
        id: 'google_drive', 
        name: 'Google Drive', 
        description: 'Fast file access, smart content search, and document management.', 
        providerId: 'google_drive', 
        category: 'all', 
        status: 'available', 
        type: 'app',
        version: 'v3', 
        color: 'bg-green-50 text-green-700',
        authType: 'oauth',
    },
    { 
        id: 'outlook_mail', 
        name: 'Outlook Mail', 
        description: 'Seamlessly write, search, and manage your Outlook emails.', 
        providerId: 'outlook_mail', 
        category: 'all', 
        status: 'available', 
        type: 'app',
        version: 'v1.0', 
        color: 'bg-blue-50 text-blue-800',
        authType: 'oauth',
    },
    { 
        id: 'outlook_calendar', 
        name: 'Outlook Calendar', 
        description: 'Just a prompt to arrange, view, and manage your Outlook schedule.', 
        providerId: 'outlook_calendar', 
        category: 'all', 
        status: 'available', 
        type: 'app',
        version: 'v1.0', 
        color: 'bg-blue-50 text-blue-800',
        authType: 'oauth',
    },
    { 
        id: 'github', 
        name: 'GitHub', 
        description: 'Manage code repositories, collaborate on development, and code review.', 
        providerId: 'github', 
        category: 'all', 
        status: 'available', 
        type: 'app',
        version: 'v3', 
        color: 'bg-gray-100 text-gray-900',
        authType: 'oauth',
    },
    { 
        id: 'slack', 
        name: 'Slack', 
        description: 'Read and write Slack conversations.', 
        providerId: 'slack', 
        category: 'all', 
        status: 'available', 
        type: 'app',
        version: 'v2', 
        color: 'bg-purple-50 text-purple-700',
        authType: 'oauth',
    },
    { 
        id: 'notion', 
        name: 'Notion', 
        description: 'Search and update content, implement automation workflows.', 
        providerId: 'notion', 
        category: 'all', 
        status: 'available', 
        type: 'app',
        version: 'v1', 
        color: 'bg-gray-50 text-gray-900',
        authType: 'oauth',
    },
    { 
        id: 'zapier', 
        name: 'Zapier', 
        description: 'Connect Manus and automate workflows between thousands of apps.', 
        providerId: 'zapier', 
        category: 'all', 
        status: 'available', 
        type: 'app',
        version: 'v1', 
        color: 'bg-orange-50 text-orange-700',
        authType: 'oauth',
    },

    // --- LLM (Global Leaders) ---
    { 
        id: 'google', 
        name: 'Google Gemini', 
        description: '多模态推理 (Gemini/Veo)，1M+ 上下文窗口，支持原生代码执行。', 
        providerId: 'google', 
        category: 'llm', 
        capabilities: ['text', 'image', 'video', 'audio'],
        status: 'available', 
        type: 'system_api',
        version: '1.5 Pro', 
        color: 'bg-white',
        authType: 'apiKey',
        docsUrl: 'https://aistudio.google.com/app/apikey',
        paramLabel: 'Gemini API 密钥',
        placeholder: 'AIzaSy...',
        validationRegex: '^AIza[0-9A-Za-z\\-_]{35}$' 
    },
    { 
        id: 'openai', 
        name: 'OpenAI', 
        description: '访问 GPT-4o、O1 和 Sora (预览) 模型。', 
        providerId: 'openai', 
        category: 'llm', 
        capabilities: ['text', 'image', 'audio', 'video'],
        status: 'available', 
        type: 'system_api',
        version: 'GPT-4o', 
        color: 'bg-green-100 text-green-700',
        authType: 'apiKey',
        docsUrl: 'https://platform.openai.com/api-keys',
        paramLabel: 'OpenAI API 密钥',
        placeholder: 'sk-...',
        validationRegex: '^sk-[a-zA-Z0-9\\-_]{30,}$'
    },
    { 
        id: 'anthropic', 
        name: 'Anthropic', 
        description: 'Claude 3.5 Sonnet & Opus. 强大的长文本与视觉理解能力。', 
        providerId: 'anthropic', 
        category: 'llm', 
        capabilities: ['text', 'image'],
        status: 'available', 
        type: 'system_api',
        version: '3.5 Sonnet', 
        color: 'bg-orange-100 text-orange-700',
        authType: 'apiKey',
        docsUrl: 'https://console.anthropic.com/settings/keys',
        paramLabel: 'Anthropic API 密钥',
        placeholder: 'sk-ant-...'
    },
    { 
        id: 'azure', 
        name: 'Microsoft Azure', 
        description: 'Azure OpenAI Service. 企业级安全与合规性支持。', 
        providerId: 'azure', 
        category: 'llm', 
        capabilities: ['text', 'image', 'audio'],
        status: 'available', 
        type: 'system_api',
        version: 'OpenAI', 
        color: 'bg-blue-50 text-blue-700',
        authType: 'apiKey',
        docsUrl: 'https://portal.azure.com/',
        paramLabel: 'API Key & Endpoint',
        placeholder: 'Endpoint | Key | Deployment'
    },
    { 
        id: 'mistral', 
        name: 'Mistral AI', 
        description: 'Mistral Large 2 与 Pixtral。高性能欧洲开源/商业模型。', 
        providerId: 'mistral', 
        category: 'llm', 
        capabilities: ['text', 'image'],
        status: 'available', 
        type: 'system_api',
        version: 'Large 2', 
        color: 'bg-yellow-100 text-yellow-700',
        authType: 'apiKey',
        docsUrl: 'https://console.mistral.ai/api-keys/'
    },
    { 
        id: 'grok', 
        name: 'xAI Grok', 
        description: '实时知识获取与不受限的创意生成。', 
        providerId: 'grok', 
        category: 'llm', 
        capabilities: ['text', 'image'],
        status: 'available', 
        type: 'system_api',
        version: 'Beta', 
        color: 'bg-gray-100 text-gray-700',
        authType: 'apiKey',
        docsUrl: 'https://x.ai/api'
    },
    { 
        id: 'meta', 
        name: 'Meta LLaMA', 
        description: 'LLaMA 3.2 与 ImageBind。开源生态基石。', 
        providerId: 'meta', 
        category: 'llm', 
        capabilities: ['text', 'image', 'audio', 'video'],
        status: 'available', 
        type: 'system_api',
        version: '3.2', 
        color: 'bg-blue-600 text-white',
        authType: 'apiKey',
        docsUrl: 'https://ai.meta.com/llama/'
    },
    { 
        id: 'aws', 
        name: 'Amazon Bedrock', 
        description: '访问 Titan, Claude, Llama 等多模型市场。', 
        providerId: 'aws', 
        category: 'llm', 
        capabilities: ['text', 'image'],
        status: 'available', 
        type: 'system_api',
        version: 'Bedrock', 
        color: 'bg-orange-400 text-white',
        authType: 'apiKey',
        docsUrl: 'https://aws.amazon.com/bedrock/'
    },

    // --- Domestic Cloud Leaders (China) ---
    { 
        id: 'aliyun', 
        name: '阿里云 (Qwen)', 
        description: '通义千问 (Qwen-Max) 与 通义万相。全能型 AI 服务。', 
        providerId: 'aliyun', 
        category: 'llm', 
        capabilities: ['text', 'image', 'audio'],
        status: 'available', 
        type: 'system_api',
        version: 'Qwen-Max', 
        color: 'bg-orange-500 text-white',
        authType: 'apiKey',
        placeholder: 'sk-................................',
        docsUrl: 'https://help.aliyun.com/zh/dashscope/'
    },
    { 
        id: 'volcengine', 
        name: '火山引擎 (Doubao)', 
        description: '豆包大模型。字节跳动出品，视频与语音能力卓越。', 
        providerId: 'volcengine', 
        category: 'llm', 
        capabilities: ['text', 'image', 'video', 'audio'],
        status: 'available', 
        type: 'system_api',
        version: 'Doubao-Pro', 
        color: 'bg-blue-500 text-white',
        authType: 'apiKey',
        docsUrl: 'https://www.volcengine.com/product/doubao'
    },
    { 
        id: 'tencent', 
        name: '腾讯云 (Hunyuan)', 
        description: '腾讯混元大模型。强大的中文理解与多媒体生成。', 
        providerId: 'tencent', 
        category: 'llm', 
        capabilities: ['text', 'image', 'video'],
        status: 'available', 
        type: 'system_api',
        version: 'Hunyuan', 
        color: 'bg-blue-600 text-white',
        authType: 'apiKey',
        docsUrl: 'https://cloud.tencent.com/product/hunyuan'
    },
    { 
        id: 'baidu', 
        name: '百度智能云 (ERNIE)', 
        description: '文心一言 4.0。知识增强大模型。', 
        providerId: 'baidu', 
        category: 'llm', 
        capabilities: ['text', 'image'],
        status: 'available', 
        type: 'system_api',
        version: 'ERNIE-4.0', 
        color: 'bg-blue-700 text-white',
        authType: 'apiKey',
        docsUrl: 'https://cloud.baidu.com/product/wenxinworkshop'
    },
    { 
        id: 'deepseek', 
        name: 'DeepSeek', 
        description: '深度求索。开源与推理能力的新标杆 (V3/R1)。', 
        providerId: 'deepseek', 
        category: 'llm', 
        capabilities: ['text'],
        status: 'available', 
        type: 'system_api',
        version: 'V3', 
        color: 'bg-blue-600 text-white',
        authType: 'apiKey',
        docsUrl: 'https://platform.deepseek.com/'
    },
    { 
        id: 'hailuo', 
        name: 'MiniMax (Hailuo)', 
        description: '海螺 AI。擅长拟人交互与高智商推理。', 
        providerId: 'hailuo', 
        category: 'llm', 
        capabilities: ['text', 'audio'],
        status: 'available', 
        type: 'system_api',
        version: 'abab6.5', 
        color: 'bg-purple-500 text-white',
        authType: 'apiKey',
        docsUrl: 'https://platform.minimaxi.com/'
    },
    { 
        id: 'siliconflow', 
        name: 'SiliconFlow', 
        description: '硅基流动。一站式高性能模型推理服务。', 
        providerId: 'siliconflow', 
        category: 'llm', 
        capabilities: ['text', 'image'],
        status: 'available', 
        type: 'system_api',
        version: 'Pro', 
        color: 'bg-purple-600 text-white',
        authType: 'apiKey',
        docsUrl: 'https://siliconflow.cn/'
    },

    // --- Image Generation ---
    { 
        id: 'midjourney', 
        name: 'Midjourney', 
        description: '最先进的艺术图像生成。需 Discord 桥接或第三方 API 代理。', 
        providerId: 'midjourney', 
        category: 'image', 
        capabilities: ['image'],
        status: 'available', 
        type: 'system_api',
        version: 'v6.1', 
        color: 'bg-blue-100 text-blue-700',
        authType: 'proxy',
        paramLabel: '代理端点 / Token'
    },
    { 
        id: 'stability', 
        name: 'Stability AI', 
        description: 'Stable Diffusion 3.5 & Stable Video. 图像与视频生成。', 
        providerId: 'stability', 
        category: 'image', 
        capabilities: ['image', 'video'],
        status: 'available', 
        type: 'system_api',
        version: 'SD 3.5', 
        color: 'bg-purple-100 text-purple-700',
        authType: 'apiKey',
        docsUrl: 'https://platform.stability.ai/account/keys'
    },
    { 
        id: 'flux', 
        name: 'Black Forest (Flux)', 
        description: 'Flux.1 Pro. 写实主义的新标准。', 
        providerId: 'flux', 
        category: 'image', 
        capabilities: ['image'],
        status: 'available', 
        type: 'system_api',
        version: 'Pro', 
        color: 'bg-emerald-100 text-emerald-700',
        authType: 'apiKey',
        paramLabel: 'BFL API 密钥',
        docsUrl: 'https://api.bfl.ml'
    },
    { 
        id: 'adobe', 
        name: 'Adobe Firefly', 
        description: 'Firefly Image 3. 商用安全的高质量图像生成。', 
        providerId: 'adobe', 
        category: 'image', 
        capabilities: ['image'],
        status: 'available', 
        type: 'system_api',
        version: 'Image 3', 
        color: 'bg-red-500 text-white',
        authType: 'apiKey',
        docsUrl: 'https://developer.adobe.com/firefly'
    },
    { 
        id: 'leonardo', 
        name: 'Leonardo.ai', 
        description: '游戏资产与概念艺术创作平台。', 
        providerId: 'leonardo', 
        category: 'image', 
        capabilities: ['image'],
        status: 'available', 
        type: 'system_api',
        version: 'Phoenix', 
        color: 'bg-pink-100 text-pink-700',
        authType: 'apiKey'
    },
    { 
        id: 'civitai', 
        name: 'Civitai', 
        description: '访问 LoRA 模型与社区 Checkpoints。', 
        providerId: 'civitai', 
        category: '3d', 
        capabilities: ['image'],
        status: 'available', 
        type: 'system_api',
        version: 'API', 
        color: 'bg-teal-100 text-teal-700',
        authType: 'apiKey'
    },

    // --- Video Generation ---
    { 
        id: 'runway', 
        name: 'Runway', 
        description: 'Gen-3 Alpha. 电影级视频生成控制。', 
        providerId: 'runway', 
        category: 'video', 
        capabilities: ['video'],
        status: 'available', 
        type: 'system_api',
        version: 'Gen-3', 
        color: 'bg-rose-100 text-rose-700',
        authType: 'apiKey',
        docsUrl: 'https://runwayml.com/'
    },
    { 
        id: 'luma', 
        name: 'Luma Dream Machine', 
        description: '快速、高质量的视频生成循环。', 
        providerId: 'luma', 
        category: 'video', 
        capabilities: ['video'],
        status: 'available', 
        type: 'system_api',
        version: 'v1.5', 
        color: 'bg-lime-100 text-lime-700',
        authType: 'apiKey',
        docsUrl: 'https://lumalabs.ai/dream-machine/api'
    },
    { 
        id: 'kling', 
        name: 'Kling AI', 
        description: '可灵 AI。长时长视频生成 (1.5 模型)。', 
        providerId: 'kling', 
        category: 'video', 
        capabilities: ['video'],
        status: 'maintenance', 
        type: 'system_api',
        version: '1.5', 
        color: 'bg-cyan-100 text-cyan-700',
        authType: 'apiKey'
    },
    { 
        id: 'pika', 
        name: 'Pika Labs', 
        description: '专注口型同步与动画的视频工具。', 
        providerId: 'pika', 
        category: 'video', 
        capabilities: ['video'],
        status: 'available', 
        type: 'system_api',
        version: 'v1.0', 
        color: 'bg-violet-100 text-violet-700',
        authType: 'apiKey'
    },

    // --- Audio ---
    { 
        id: 'elevenlabs', 
        name: 'ElevenLabs', 
        description: '业界领先的语音合成与音效生成。', 
        providerId: 'elevenlabs', 
        category: 'audio', 
        capabilities: ['audio'],
        status: 'available', 
        type: 'system_api',
        version: 'v2', 
        color: 'bg-indigo-100 text-indigo-700',
        authType: 'apiKey',
        docsUrl: 'https://elevenlabs.io/app/settings/api-keys'
    },
    { 
        id: 'suno', 
        name: 'Suno', 
        description: '全曲生成，包含歌词与人声。', 
        providerId: 'suno', 
        category: 'audio', 
        capabilities: ['audio'],
        status: 'available', 
        type: 'system_api',
        version: 'v3.5', 
        color: 'bg-amber-100 text-amber-700',
        authType: 'proxy'
    },
    { 
        id: 'udio', 
        name: 'Udio', 
        description: '高保真音乐生成。', 
        providerId: 'udio', 
        category: 'audio', 
        capabilities: ['audio'],
        status: 'available', 
        type: 'system_api',
        version: 'Beta', 
        color: 'bg-red-100 text-red-700',
        authType: 'proxy'
    },

    // --- Aggregators & Platforms ---
    { 
        id: 'replicate', 
        name: 'Replicate', 
        description: '运行开源模型的云平台 (Llama, Flux, SDXL)。', 
        providerId: 'replicate', 
        category: 'llm', 
        capabilities: ['text', 'image', 'video', 'audio'],
        status: 'available', 
        type: 'system_api',
        version: 'API', 
        color: 'bg-gray-800 text-white',
        authType: 'apiKey',
        docsUrl: 'https://replicate.com/account/api-tokens'
    },
    { 
        id: 'fal', 
        name: 'Fal.ai', 
        description: '最快的媒体生成推理云 (Flux, SD3, Kling)。', 
        providerId: 'fal', 
        category: 'image', 
        capabilities: ['image', 'video'],
        status: 'available', 
        type: 'system_api',
        version: 'API', 
        color: 'bg-purple-800 text-white',
        authType: 'apiKey',
        docsUrl: 'https://fal.ai/dashboard/keys'
    },
    { 
        id: 'openrouter', 
        name: 'OpenRouter', 
        description: '统一接口访问所有 LLM (GPT, Claude, Llama, Mistral)。', 
        providerId: 'openrouter', 
        category: 'llm', 
        capabilities: ['text'],
        status: 'available', 
        type: 'system_api',
        version: 'API', 
        color: 'bg-green-600 text-white',
        authType: 'apiKey',
        docsUrl: 'https://openrouter.ai/keys'
    },
    { 
        id: 'huggingface', 
        name: 'Hugging Face', 
        description: '访问数千个开源模型 (Inference API)。', 
        providerId: 'huggingface', 
        category: '3d', 
        capabilities: ['text', 'image'],
        status: 'available', 
        type: 'system_api',
        version: 'Hub', 
        color: 'bg-yellow-100 text-yellow-800',
        authType: 'apiKey',
        docsUrl: 'https://huggingface.co/settings/tokens'
    },
];
